from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('events/', views.all_events_view, name='all_events'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/bookings/', views.manage_bookings_view, name='manage_bookings'),
    path('dashboard/bookings/total/', views.total_bookings_view, name='total_bookings'),
    path('dashboard/bookings/add/', views.add_booking_view, name='add_booking'),
    path('dashboard/bookings/<int:booking_id>/edit/', views.edit_booking_view, name='edit_booking'),
    path('dashboard/bookings/<int:booking_id>/delete/', views.delete_booking_view, name='delete_booking'),
    path('dashboard/events/', views.manage_events_view, name='manage_events'),
    path('dashboard/events/add/', views.add_event_view, name='add_event'),
    path('dashboard/events/<int:event_id>/edit/', views.edit_event_view, name='edit_event'),
    path('dashboard/events/<int:event_id>/delete/', views.delete_event_view, name='delete_event'),
    path('dashboard/gallery/', views.manage_gallery_view, name='manage_gallery'),
    path('dashboard/gallery/add/', views.add_gallery_image_view, name='add_gallery_image'),
    path('dashboard/gallery/<int:image_id>/edit/', views.edit_gallery_image_view, name='edit_gallery_image'),
    path('dashboard/gallery/<int:image_id>/delete/', views.delete_gallery_image_view, name='delete_gallery_image'),
    path('dashboard/artists/', views.manage_artists_view, name='manage_artists'),
    path('dashboard/artists/add/', views.add_artist_view, name='add_artist'),
    path('dashboard/artists/<int:artist_id>/edit/', views.edit_artist_view, name='edit_artist'),
    path('dashboard/artists/<int:artist_id>/delete/', views.delete_artist_view, name='delete_artist'),
    path('dashboard/settings/', views.dashboard_settings_view, name='dashboard_settings'),
    path('dashboard/calendar/', views.admin_calendar_view, name='admin_calendar'),
    path('dashboard/accounts/', views.admin_accounts_view, name='admin_accounts'),
    path('dashboard/employees/', views.manage_employees_view, name='manage_employees'),
    path('dashboard/employees/follow-ups/', views.follow_up_status_view, name='follow_up_status'),
    path('dashboard/employees/add/', views.add_employee_view, name='add_employee'),
    path('dashboard/employees/<int:employee_id>/edit/', views.edit_employee_view, name='edit_employee'),
    path('dashboard/employees/<int:employee_id>/delete/', views.delete_employee_view, name='delete_employee'),
    path('dashboard/crm/', views.admin_crm_view, name='admin_crm'),
    path('dashboard/crm/conversions/', views.admin_crm_conversion_view, name='admin_crm_conversion'),
    
    # Employee Portal Routes
    path('employee/dashboard/', views.employee_dashboard_view, name='employee_dashboard'),
    path('employee/notifications/seen/', views.employee_notifications_seen_view, name='employee_notifications_seen'),
    path('employee/calendar/', views.employee_calendar_view, name='employee_calendar'),
    path('employee/bookings/', views.employee_bookings_view, name='employee_bookings'),
    path('employee/crm/', views.employee_crm_view, name='employee_crm'),
    # Artist Portal Routes
    path('artist/dashboard/', views.artist_dashboard_view, name='artist_dashboard'),
    path('artist/calendar/', views.artist_calendar_view, name='artist_calendar'),
    path('artist/accounts/', views.artist_accounts_view, name='artist_accounts'),
    path('artist/earnings/', views.artist_earnings_view, name='artist_earnings'),
    
    path('api/artists/', views.api_artists, name='api_artists'),
    path('api/bookings/', views.api_bookings, name='api_bookings'),
    path('api/artist/calendar/', views.api_artist_calendar_events, name='api_artist_calendar_events'),
    path('api/artist/calendar/busy/add/', views.api_add_busy_date, name='api_add_busy_date'),
    path('api/artist/calendar/busy/remove/', views.api_remove_busy_date, name='api_remove_busy_date'),
]
