# Generated by Django 6.0 on 2026-05-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(help_text='Emoji or short string', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#7C3AED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('performance', 'Performance'), ('shoot', 'Shoot'), ('vacation', 'Vacation'), ('travel', 'Travel'), ('other', 'Other')], default='performance', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.artist')),
            ],
        ),
    ]
