# Generated by Django 6.0 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wild High Nights', max_length=200)),
                ('instagram_link', models.URLField(default='https://instagram.com/wildhighnights')),
                ('contact_email', models.EmailField(default='info@wildhighnights.com', max_length=254)),
                ('footer_description', models.TextField(default='Discover unforgettable nightlife experiences, artists, DJs, and exclusive events across the globe.')),
                ('hero_text', models.TextField(default='Discover unforgettable nightlife experiences, artists, DJs, and exclusive events across Ireland.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
