# Generated by Django 6.0 on 2026-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
