# Generated by Django 6.0 on 2026-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_artist_artist_image_artist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com/whn_wild_high_nights?igsh=MXJoODl5NTlnc2J5ZQ%3D%3D'),
        ),
    ]
