# Generated by Django 6.0 on 2026-05-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_artist_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='color',
        ),
    ]
