# Generated by Django 6.0 on 2026-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_activitylog_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
