# Generated by Django 6.0 on 2026-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_event_alter_sitesettings_hero_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='event_image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='event_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='venue_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=20),
        ),
    ]
