# Generated by Django 6.0 on 2026-05-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking_docs/accommodation/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='artwork_attachment',
            field=models.FileField(blank=True, null=True, upload_to='booking_docs/artwork/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Lead', 'Lead')], default='Sale', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='deal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='deal_type',
            field=models.CharField(choices=[('++ Deal', '++ Deal'), ('All Inclusive Deal', 'All Inclusive Deal'), ('Landed Deal', 'Landed Deal')], default='Landed Deal', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Campus', 'Campus'), ('Club', 'Club')], default='Club', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='ground_transport',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='ground_transport_attachment',
            field=models.FileField(blank=True, null=True, upload_to='booking_docs/transport/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sound_check',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking_docs/travel/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Tentative', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='bookings.booking')),
            ],
        ),
    ]
