# Generated by Django 6.0 on 2026-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_booking_type_booking_accommodation_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accommodation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
