# Generated by Django 6.0 on 2026-05-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_accommodation_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ground_transport_attachment',
        ),
    ]
