# Generated by Django 6.0 on 2026-05-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_remove_booking_ground_transport_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('busy', 'Busy')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.artist')),
            ],
            options={
                'unique_together': {('artist', 'date')},
            },
        ),
    ]
