# Generated by Django 6.0 on 2026-05-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_artistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_artist_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Lead', 'Lead'), ('Custom', 'Custom')], default='Sale', max_length=10),
        ),
    ]
