# Generated by Django 5.1.7 on 2026-06-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_clientlead_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlead',
            name='event_date',
        ),
    ]
