# Generated by Django 5.1.7 on 2026-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_remove_clientlead_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingexpense',
            name='borne_by',
            field=models.CharField(choices=[('Artist', 'Artist'), ('WHN', 'WHN')], default='WHN', max_length=10),
        ),
    ]
